version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2user/
hooks:
  ApplicationStart:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

