version: 0.0
os: linux
files:
  - source: /index.yml
    destination: /var/www/html
hooks:
  ApplicationStart:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root

